#!/bin/bash
# put this file in /etc/init.d/
APP_NAME=droidcon-poland
APP_DEFAULT_ENV=production
SYSTEM_USER=rails
DIR=/home/${SYSTEM_USER}/${APP_NAME}/current
PID_FILE=${DIR}/tmp/pids/${APP_NAME}-unicorn.pid

case $1 in
  start)
      su -l -c "cd $DIR && RAILS_ENV=$APP_DEFAULT_ENV bundle exec unicorn -c config/unicorn/production.rb -D" root >/dev/null 2>&1
      ;;
  stop)
      if [ -e $PID_FILE ]; then kill `cat $PID_FILE`; fi;;
     *)
      echo "usage: unicorn-$APP_NAME {start|stop}" ;;
esac
exit 0
